'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class abml_creditos

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Txt_cliente_codigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_cliente_codigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lb_error_codigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_error_codigo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_fecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lb_error_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_error_fecha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_cliente_nomb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_cliente_nomb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txt_importe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_importe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lb_error_importe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_error_importe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_porcentaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_porcentaje As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lb_error_porcentaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_error_porcentaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_diasacobrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_diasacobrar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lb_error_dias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_error_dias As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_retroceder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_retroceder As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BOTON_GRABA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BOTON_GRABA As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_close_error_limite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_error_limite As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_ok_error_limite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ok_error_limite As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_close_error_ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_error_ingreso As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_ok_error_ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ok_error_ingreso As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_close_error_noexiste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_error_noexiste As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_ok_error_noexiste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ok_error_noexiste As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_close_error_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_error_fecha As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_ok_error_fecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ok_error_fecha As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_alta_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_alta_close As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_alta_cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_alta_cancelar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_alta_confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_alta_confirmar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_modif_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_modif_close As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_modif_cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_modif_cancelar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_modif_confirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_modif_confirmar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_graba_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_graba_close As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_ok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ok As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
